version: 2.1
orbs:
  samvera: samvera/circleci-orb@0
jobs:
  build:
    executor:
      name: 'samvera/ruby'
      ruby_version: "2.5.7"

    working_directory: ~/repo

    steps:
      - samvera/cached_checkout
      - samvera/bundle_for_gem:
          ruby_version: "2.5.7"
          bundler_version: "1.17"
          project: ldpath
      - samvera/parallel_rspec

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
